export interface Database {
  public: {
    Tables: {
      users: {
        Row: {
          id: string;
          netlify_id: string | null;
          email: string;
          first_name: string;
          last_name: string;
          phone: string | null;
          date_of_birth: string | null;
          profile_image_url: string | null;
          preferences: any;
          created_at: string;
          updated_at: string;
          last_login: string | null;
          email_verified: boolean;
          status: string;
        };
        Insert: {
          id?: string;
          netlify_id?: string | null;
          email: string;
          first_name?: string;
          last_name?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          profile_image_url?: string | null;
          preferences?: any;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          email_verified?: boolean;
          status?: string;
        };
        Update: {
          id?: string;
          netlify_id?: string | null;
          email?: string;
          first_name?: string;
          last_name?: string;
          phone?: string | null;
          date_of_birth?: string | null;
          profile_image_url?: string | null;
          preferences?: any;
          created_at?: string;
          updated_at?: string;
          last_login?: string | null;
          email_verified?: boolean;
          status?: string;
        };
      };
      venues: {
        Row: {
          id: string;
          name: string;
          address: string;
          city: string;
          country: string;
          postal_code: string | null;
          latitude: number | null;
          longitude: number | null;
          capacity: number;
          description: string | null;
          amenities: any;
          contact_info: any;
          images: any;
          created_at: string;
          updated_at: string;
          status: string;
        };
        Insert: {
          id?: string;
          name: string;
          address: string;
          city: string;
          country?: string;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          capacity?: number;
          description?: string | null;
          amenities?: any;
          contact_info?: any;
          images?: any;
          created_at?: string;
          updated_at?: string;
          status?: string;
        };
        Update: {
          id?: string;
          name?: string;
          address?: string;
          city?: string;
          country?: string;
          postal_code?: string | null;
          latitude?: number | null;
          longitude?: number | null;
          capacity?: number;
          description?: string | null;
          amenities?: any;
          contact_info?: any;
          images?: any;
          created_at?: string;
          updated_at?: string;
          status?: string;
        };
      };
      events: {
        Row: {
          id: string;
          title: string;
          description: string;
          short_description: string | null;
          date: string;
          time: string;
          end_time: string | null;
          venue_id: string | null;
          venue_name: string;
          venue_address: string;
          venue_city: string;
          image_url: string | null;
          gallery_images: any;
          category: string;
          tags: any;
          age_restriction: string | null;
          dress_code: string | null;
          special_instructions: string | null;
          status: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          published_at: string | null;
          sales_start_date: string | null;
          sales_end_date: string | null;
          max_tickets_per_order: number;
          is_featured: boolean;
          metadata: any;
        };
        Insert: {
          id?: string;
          title: string;
          description: string;
          short_description?: string | null;
          date: string;
          time: string;
          end_time?: string | null;
          venue_id?: string | null;
          venue_name: string;
          venue_address: string;
          venue_city: string;
          image_url?: string | null;
          gallery_images?: any;
          category: string;
          tags?: any;
          age_restriction?: string | null;
          dress_code?: string | null;
          special_instructions?: string | null;
          status?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          sales_start_date?: string | null;
          sales_end_date?: string | null;
          max_tickets_per_order?: number;
          is_featured?: boolean;
          metadata?: any;
        };
        Update: {
          id?: string;
          title?: string;
          description?: string;
          short_description?: string | null;
          date?: string;
          time?: string;
          end_time?: string | null;
          venue_id?: string | null;
          venue_name?: string;
          venue_address?: string;
          venue_city?: string;
          image_url?: string | null;
          gallery_images?: any;
          category?: string;
          tags?: any;
          age_restriction?: string | null;
          dress_code?: string | null;
          special_instructions?: string | null;
          status?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          published_at?: string | null;
          sales_start_date?: string | null;
          sales_end_date?: string | null;
          max_tickets_per_order?: number;
          is_featured?: boolean;
          metadata?: any;
        };
      };
      sections: {
        Row: {
          id: string;
          event_id: string | null;
          venue_id: string | null;
          name: string;
          type: string;
          price: number;
          capacity: number;
          description: string | null;
          color: string;
          position_data: any;
          amenities: any;
          created_at: string;
          updated_at: string;
          is_active: boolean;
        };
        Insert: {
          id?: string;
          event_id?: string | null;
          venue_id?: string | null;
          name: string;
          type: string;
          price: number;
          capacity?: number;
          description?: string | null;
          color?: string;
          position_data?: any;
          amenities?: any;
          created_at?: string;
          updated_at?: string;
          is_active?: boolean;
        };
        Update: {
          id?: string;
          event_id?: string | null;
          venue_id?: string | null;
          name?: string;
          type?: string;
          price?: number;
          capacity?: number;
          description?: string | null;
          color?: string;
          position_data?: any;
          amenities?: any;
          created_at?: string;
          updated_at?: string;
          is_active?: boolean;
        };
      };
      seats: {
        Row: {
          id: string;
          section_id: string | null;
          row_name: string;
          seat_number: number;
          status: string;
          position_x: number;
          position_y: number;
          reserved_until: string | null;
          reserved_by: string | null;
          accessibility_features: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          section_id?: string | null;
          row_name: string;
          seat_number: number;
          status?: string;
          position_x?: number;
          position_y?: number;
          reserved_until?: string | null;
          reserved_by?: string | null;
          accessibility_features?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          section_id?: string | null;
          row_name?: string;
          seat_number?: number;
          status?: string;
          position_x?: number;
          position_y?: number;
          reserved_until?: string | null;
          reserved_by?: string | null;
          accessibility_features?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
      orders: {
        Row: {
          id: string;
          user_id: string | null;
          event_id: string | null;
          order_number: string;
          status: string;
          subtotal: number;
          service_fee: number;
          taxes: number;
          total_amount: number;
          currency: string;
          payment_method: string | null;
          payment_id: string | null;
          payment_status: string;
          billing_info: any;
          notes: string | null;
          expires_at: string | null;
          completed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          event_id?: string | null;
          order_number: string;
          status?: string;
          subtotal?: number;
          service_fee?: number;
          taxes?: number;
          total_amount?: number;
          currency?: string;
          payment_method?: string | null;
          payment_id?: string | null;
          payment_status?: string;
          billing_info?: any;
          notes?: string | null;
          expires_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          event_id?: string | null;
          order_number?: string;
          status?: string;
          subtotal?: number;
          service_fee?: number;
          taxes?: number;
          total_amount?: number;
          currency?: string;
          payment_method?: string | null;
          payment_id?: string | null;
          payment_status?: string;
          billing_info?: any;
          notes?: string | null;
          expires_at?: string | null;
          completed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
      };
      tickets: {
        Row: {
          id: string;
          order_id: string | null;
          event_id: string | null;
          section_id: string | null;
          seat_id: string | null;
          ticket_number: string;
          price: number;
          status: string;
          qr_code: string | null;
          barcode: string | null;
          used_at: string | null;
          used_by: string | null;
          transfer_history: any;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          order_id?: string | null;
          event_id?: string | null;
          section_id?: string | null;
          seat_id?: string | null;
          ticket_number: string;
          price: number;
          status?: string;
          qr_code?: string | null;
          barcode?: string | null;
          used_at?: string | null;
          used_by?: string | null;
          transfer_history?: any;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          order_id?: string | null;
          event_id?: string | null;
          section_id?: string | null;
          seat_id?: string | null;
          ticket_number?: string;
          price?: number;
          status?: string;
          qr_code?: string | null;
          barcode?: string | null;
          used_at?: string | null;
          used_by?: string | null;
          transfer_history?: any;
          created_at?: string;
          updated_at?: string;
        };
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      [_ in never]: never;
    };
    Enums: {
      [_ in never]: never;
    };
  };
}